---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: cs-pvc
  labels:
    app: codeserver
    name: cs-pvc
  namespace: cs
spec: 
  accessModes:
  - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi
  storageClassName: do-block-storage-xfs
---
