apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy-deploy
  labels:
    name: mydeploy-deploy
  namespace: myns2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mypod-po
  template:
    metadata:
      name: mypod-po
      labels:
        name: mypod-po
    spec:
      containers:
      - name: mypod-container
        image: chukmunnlee/dov-bear-golang:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: mypod
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "curl -s -f http://localhost:$(PORT)/healthz/ || exit 1"
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    name: myservice
  namespace: myns2
spec:
  type: ClusterIP
  selector:
    name: mypod-po
  ports:
  - port: 3000
    targetPort: 3000
