apiVersion: v1
kind: Pod
metadata:
  name: mypod-po
  labels:
    name: mypod-po
  namespace: myns2
spec:
  containers:
  - name: mypod-container
    image: chukmunnlee/dov-bear-golang:0.1
    imagePullPolicy: IfNotPresent
    env:
    - name: INSTANCE_NAME
      value: mypod
    - name: INSTANCE_HASH
      value: abc123
    ports:
    - containerPort: 3000
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000