apiVersion: v1
kind: PersistentVolumeClaim
meta-data:
  name: db-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "provisioner"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard