---
apiVersion: v1
kind: Service
metadata:
  name: osc-svc
  labels:
    name: osc-svc
    app: minio
  namespace: osc
spec:
  type: ClusterIP
  selector:
    name: osc-po
    app: minio
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osc-ing
  labels:
    name: osc-ing
  namespace: osc
spec:
  ingressClassName: nginx
  rules:
  - host: data-137.184.251.193.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: osc-svc
            port:
              name: data
  - host: console-137.184.251.193.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: osc-svc
            port:
              name: console